export {
  addItemToKnowledge,
  boostPreference,
  createItem,
  createItemsBatch,
  getCollectorItemAttempts,
  getItem,
  getItemDiagnostics,
  getPreferenceSummary,
  interpretItem,
  listItems,
  listSavedItems,
  reprocessItem,
  reprocessItemsBatch,
  resetPreferences,
  submitFeedback,
} from "@/lib/api/items";

export {
  createResearchReport,
  createResearchJob,
  getResearchJob,
  getResearchJobClarification,
  getResearchJobTimeline,
  submitResearchJobClarification,
  submitResearchExperienceFeedback,
  getResearchExperienceMetrics,
  getResearchExperienceReadiness,
  listResearchConversations,
  createResearchConversation,
  getResearchConversation,
  sendResearchConversationMessage,
  getMobileDailyBrief,
  getResearchDailyBrief,
  getResearchSourceSettings,
  updateResearchSourceSettings,
  getResearchWorkspace,
  getLowQualityResearchReviewQueue,
  getResearchOfflineEvaluation,
  getResearchGoldenEvaluation,
  getResearchExperimentControlPlane,
  getResearchExperimentOrchestration,
  getResearchExperimentActivePolicies,
  getResearchExperimentRuntimeSnapshot,
  getResearchExperimentRuntimeConfig,
  createResearchExperimentPlan,
  freezeResearchExperimentCohort,
  lockResearchExperimentBaseline,
  evaluateResearchExperimentGate,
  promoteResearchExperimentRollout,
  revokeResearchExperimentRollout,
  getResearchFollowupDeltaEvaluation,
  getResearchDeliveryExportDiagnostics,
  getResearchUpgradeDiagnosticsPreview,
  getResearchAssurancePreview,
  getResearchIndustrySkills,
  searchResearchIndustryKnowledge,
  getResearchIndustryKnowledgeRetrievalBenchmark,
  runResearchIndustryKnowledgeRetrievalBenchmark,
  getResearchIndustryKnowledgeRetrievalAssurance,
  exportResearchIndustryKnowledgeRetrievalApprovalTemplate,
  exportResearchIndustryKnowledgeRetrievalEvidenceTemplates,
  getResearchIndustryKnowledgeRetrievalEvidenceOperations,
  exportResearchIndustryKnowledgeRetrievalEvidenceOperationsTemplates,
  buildResearchIndustryKnowledgeDeliveryReview,
  buildResearchSectionRetrievalPacks,
  buildResearchSolutionDeliveryPack,
  refreshResearchSolutionIntelligence,
  rebuildResearchRetrievalIndex,
  getResearchRetrievalIndexStatus,
  searchResearchRetrievalIndex,
  rewriteLowQualityResearchReviewItem,
  resolveLowQualityResearchReviewItem,
  createResearchCompareSnapshot,
  getResearchCompareSnapshot,
  deleteResearchCompareSnapshot,
  createResearchMarkdownArchive,
  getResearchMarkdownArchive,
  deleteResearchMarkdownArchive,
  listResearchWatchlists,
  getResearchWatchlistAutomationStatus,
  getResearchWatchlistOpsSummary,
  createResearchWatchlist,
  updateResearchWatchlist,
  getResearchWatchlistChanges,
  refreshResearchWatchlist,
  runDueResearchWatchlists,
  getResearchWatchlistRunHistory,
  getResearchWatchlistDigestExport,
  getResearchEntityDetail,
  resolveResearchEntityAlias,
  saveResearchView,
  deleteResearchView,
  saveResearchTrackingTopic,
  deleteResearchTrackingTopic,
  refreshResearchTrackingTopic,
  getResearchTrackingTopicVersions,
  getResearchTrackingTopicTimeline,
  getResearchTrackingTopicVersion,
  saveResearchReport,
  createResearchActionPlan,
  saveResearchActionCards,
} from "@/lib/api/research";

export {
  listKnowledgeEntries,
  getKnowledgeEntry,
  getKnowledgeDashboard,
  listKnowledgeAccounts,
  getKnowledgeAccountDetail,
  listKnowledgeOpportunities,
  getKnowledgeMarkdown,
  listRelatedKnowledgeEntries,
  updateKnowledgeEntry,
  resolveKnowledgeReviewQueueItem,
  mergeKnowledgeEntries,
  getKnowledgeMergePreview,
  getKnowledgeRule,
  updateKnowledgeRule,
} from "@/lib/api/knowledge";

export {
  getCollectorStatus,
  getCollectorDaemonStatus,
  getCollectorDaemonConfig,
  updateCollectorDaemonConfig,
  verifyCollectorBrowserExtension,
  startCollectorDaemon,
  stopCollectorDaemon,
  runCollectorDaemonOnce,
  getWechatAgentStatus,
  getWechatAgentConfig,
  updateWechatAgentConfig,
  getWechatAgentCapturePreview,
  getWechatAgentOCRPreview,
  getWechatAgentHealth,
  runWechatAgentSelfHeal,
  startWechatAgent,
  stopWechatAgent,
  runWechatAgentOnce,
  getWechatAgentBatchStatus,
  getWechatAgentDedupSummary,
  resetWechatAgentDedupSummary,
  runWechatAgentBatch,
  processCollectorPending,
  listCollectorFailed,
  retryCollectorFailed,
  getCollectorDailySummary,
  listCollectorSources,
  createCollectorSource,
  importCollectorSources,
  updateCollectorSource,
  deleteCollectorSource,
  listCollectorFeedSources,
  createCollectorRssSource,
  pullCollectorRssFeeds,
  ingestNewsletter,
  uploadCollectorFile,
  ingestYouTubeTranscript,
  importWechatFavorites,
  previewWechatFavorites,
  listWechatFavoriteImportBatches,
  getWechatFavoriteImportBatch,
} from "@/lib/api/collector";

export {
  createFocusAssistantPlan,
  executeFocusAssistantAction,
  finishSession,
  getLatestSession,
  getSession,
  getSessionArtifacts,
  importTodoCalendar,
  pauseSession,
  previewTodoCalendarImport,
  resumeSession,
  startSession,
} from "@/lib/api/sessions";

export {
  createTask,
  getTask,
  getWorkBuddyHealth,
  sendWorkBuddyWebhook,
} from "@/lib/api/tasks";

export {
  getApiHealth,
  getInternalSkillGovernance,
  getLLMConfig,
  getModelControlPlane,
  getReleaseReadiness,
  runLLMDryRun,
  scanSupportedModels,
  upgradeToStrongestModels,
} from "@/lib/api/system";

export {
  getCompetitiveLandscape,
  getCompetitiveLandscapePreview,
  seedCompetitiveLandscape,
} from "@/lib/api/competitive-intelligence";

export type * from "@/lib/api/types";
export type * from "@/lib/api/type-contracts/competitive-intelligence";

export function toFeedCardLabel(action: string | null): "立即深读" | "稍后精读" | "可放心忽略" {
  if (action === "deep_read") return "立即深读";
  if (action === "later") return "稍后精读";
  return "可放心忽略";
}
