import type { AppLanguage } from "@/lib/preferences";
import { pickText } from "@/components/settings/collector-ops-panel-utils";

const COLLECTOR_OPS_COPY: Record<string, Partial<Record<AppLanguage, string>>> = {
    title: {
      "zh-CN": "Collector 运维面板",
      "zh-TW": "Collector 運維面板",
      en: "Collector Ops Panel",
      ja: "Collector 運用パネル",
      ko: "Collector 운영 패널",
    },
    description: {
      "zh-CN": "用于管理采集质量：补偿 pending、重试 failed、生成日报 Markdown。",
      "zh-TW": "用於管理採集品質：補償 pending、重試 failed、生成日報 Markdown。",
      en: "Manage collector quality: flush pending, retry failed, generate daily Markdown.",
      ja: "収集品質管理: pending補完、failed再試行、日次Markdown生成。",
      ko: "수집 품질 관리: pending 보정, failed 재시도, 일일 Markdown 생성.",
    },
    daemonTitle: {
      "zh-CN": "采集器守护进程",
      "zh-TW": "採集器守護進程",
      en: "Collector Daemon",
      ja: "収集デーモン",
      ko: "수집 데몬",
    },
    daemonRunning: {
      "zh-CN": "运行中",
      "zh-TW": "運行中",
      en: "Running",
      ja: "稼働中",
      ko: "실행 중",
    },
    daemonStopped: {
      "zh-CN": "已停止",
      "zh-TW": "已停止",
      en: "Stopped",
      ja: "停止中",
      ko: "중지됨",
    },
    startDaemon: {
      "zh-CN": "启动采集器",
      "zh-TW": "啟動採集器",
      en: "Start",
      ja: "開始",
      ko: "시작",
    },
    stopDaemon: {
      "zh-CN": "停止采集器",
      "zh-TW": "停止採集器",
      en: "Stop",
      ja: "停止",
      ko: "중지",
    },
    runOnce: {
      "zh-CN": "执行单轮采集",
      "zh-TW": "執行單輪採集",
      en: "Run Once",
      ja: "単発実行",
      ko: "1회 실행",
    },
    daemonPid: {
      "zh-CN": "进程 PID",
      "zh-TW": "進程 PID",
      en: "PID",
      ja: "PID",
      ko: "PID",
    },
    daemonUptime: {
      "zh-CN": "运行时长",
      "zh-TW": "運行時長",
      en: "Uptime",
      ja: "稼働時間",
      ko: "가동 시간",
    },
    daemonSources: {
      "zh-CN": "源文件 URL 数",
      "zh-TW": "來源檔 URL 數",
      en: "Source URLs",
      ja: "ソースURL数",
      ko: "소스 URL 수",
    },
    daemonLastReport: {
      "zh-CN": "最近报告",
      "zh-TW": "最近報告",
      en: "Latest report",
      ja: "最新レポート",
      ko: "최근 리포트",
    },
    daemonLastDaily: {
      "zh-CN": "最近日报",
      "zh-TW": "最近日報",
      en: "Latest daily summary",
      ja: "最新日次",
      ko: "최근 일일 요약",
    },
    daemonLastRun: {
      "zh-CN": "最近一轮",
      "zh-TW": "最近一輪",
      en: "Latest run",
      ja: "直近の実行",
      ko: "최근 실행",
    },
    daemonSubmitMode: {
      "zh-CN": "提交模式",
      "zh-TW": "提交模式",
      en: "Submit mode",
      ja: "送信モード",
      ko: "제출 모드",
    },
    daemonDiscovered: {
      "zh-CN": "发现文章",
      "zh-TW": "發現文章",
      en: "Discovered",
      ja: "検出記事",
      ko: "발견 기사",
    },
    daemonCollected: {
      "zh-CN": "提交总数",
      "zh-TW": "提交總數",
      en: "Collected",
      ja: "送信総数",
      ko: "제출 합계",
    },
    daemonPluginCount: {
      "zh-CN": "Browser Plugin",
      "zh-TW": "Browser Plugin",
      en: "Browser plugin",
      ja: "Browser plugin",
      ko: "Browser plugin",
    },
    daemonUrlFallbackCount: {
      "zh-CN": "链接补录",
      "zh-TW": "連結補錄",
      en: "URL recovery",
      ja: "URL recovery",
      ko: "URL recovery",
    },
    daemonFailedCount: {
      "zh-CN": "失败数",
      "zh-TW": "失敗數",
      en: "Failed",
      ja: "失敗数",
      ko: "실패 수",
    },
    daemonCoverageRate: {
      "zh-CN": "处理覆盖",
      "zh-TW": "處理覆蓋",
      en: "Coverage",
      ja: "処理カバレッジ",
      ko: "처리 커버리지",
    },
    daemonBodyRate: {
      "zh-CN": "正文命中",
      "zh-TW": "正文命中",
      en: "Body hit rate",
      ja: "本文取得率",
      ko: "본문 적중률",
    },
    daemonHandledCount: {
      "zh-CN": "已处理/跳过",
      "zh-TW": "已處理/跳過",
      en: "Handled / skipped",
      ja: "処理/スキップ済み",
      ko: "처리/건너뜀",
    },
    daemonRecentRows: {
      "zh-CN": "最近 batch 结果",
      "zh-TW": "最近 batch 結果",
      en: "Recent batch results",
      ja: "直近 batch 結果",
      ko: "최근 batch 결과",
    },
    daemonSourceHealth: {
      "zh-CN": "源页面健康度",
      "zh-TW": "源頁面健康度",
      en: "Source health",
      ja: "ソース健全性",
      ko: "소스 상태",
    },
    daemonLogTail: {
      "zh-CN": "最近日志",
      "zh-TW": "最近日誌",
      en: "Recent logs",
      ja: "直近ログ",
      ko: "최근 로그",
    },
    daemonOutput: {
      "zh-CN": "执行输出",
      "zh-TW": "執行輸出",
      en: "Command output",
      ja: "実行出力",
      ko: "실행 출력",
    },
    wechatAgentTitle: {
      "zh-CN": "微信 PC 自动采集",
      "zh-TW": "微信 PC 自動採集",
      en: "WeChat PC Auto Collection",
      ja: "WeChat PC 全自動 Agent",
      ko: "WeChat PC 풀오토 Agent",
    },
    wechatAgentHint: {
      "zh-CN": "自动打开公众号列表，优先提取文章链接并入库；只有明确开启时才使用 OCR 补录。连续命中同一篇时会自动加大翻页幅度。需先给 Terminal/IDE 开启辅助功能与屏幕录制权限。",
      "zh-TW": "自動打開公眾號列表，優先提取文章連結並入庫；只有明確開啟時才使用 OCR 補錄。連續命中同一篇時會自動加大翻頁幅度。需先為 Terminal/IDE 開啟輔助功能與螢幕錄製權限。",
      en: "Auto clicks the OA list, prioritizes real article URLs, and only falls back to OCR when explicitly enabled. Repeated hits on the same article now trigger larger list jumps. Requires Accessibility + Screen Recording permissions.",
      ja: "公式アカウント一覧を自動クリックし、まず実URLの取得を優先し、明示的に有効化した場合のみOCRにフォールバックします。同じ記事を連続で拾った場合は自動で送り幅を広げます。Accessibility と Screen Recording 権限が必要です。",
      ko: "공식계정 목록을 자동 클릭하고 실제 링크 추출을 우선하며, 명시적으로 켠 경우에만 OCR 폴백을 사용합니다. 같은 글이 반복되면 목록 점프 폭을 자동으로 키웁니다. 접근성/화면 녹화 권한이 필요합니다.",
    },
    wechatAgentStart: {
      "zh-CN": "启动微信采集",
      "zh-TW": "啟動微信採集",
      en: "Start WeChat Collection",
      ja: "WeChat Agent 開始",
      ko: "WeChat Agent 시작",
    },
    wechatAgentStop: {
      "zh-CN": "停止微信采集",
      "zh-TW": "停止微信採集",
      en: "Stop WeChat Collection",
      ja: "WeChat Agent 停止",
      ko: "WeChat Agent 중지",
    },
    wechatAgentRunOnce: {
      "zh-CN": "单轮扫描",
      "zh-TW": "單輪掃描",
      en: "Run Single Cycle",
      ja: "単発スキャン",
      ko: "1회 스캔",
    },
    wechatAgentRunBatch: {
      "zh-CN": "分段扫描 18 篇",
      "zh-TW": "分段掃描 18 篇",
      en: "Segmented Scan 18",
      ja: "分割スキャン 18",
      ko: "분할 스캔 18",
    },
    wechatAgentBatchTitle: {
      "zh-CN": "最近一轮分段批处理",
      "zh-TW": "最近一輪分段批處理",
      en: "Latest segmented batch",
      ja: "直近の分割バッチ",
      ko: "최근 분할 배치",
    },
    wechatAgentBatchProgress: {
      "zh-CN": "进度",
      "zh-TW": "進度",
      en: "Progress",
      ja: "進捗",
      ko: "진행률",
    },
    wechatAgentBatchSubmittedNew: {
      "zh-CN": "真正新增",
      "zh-TW": "真正新增",
      en: "New",
      ja: "新規",
      ko: "신규",
    },
    wechatAgentBatchDedup: {
      "zh-CN": "历史去重",
      "zh-TW": "歷史去重",
      en: "Deduplicated",
      ja: "既存重複",
      ko: "중복",
    },
    wechatAgentBatchSeen: {
      "zh-CN": "已跳过",
      "zh-TW": "已跳過",
      en: "Skipped",
      ja: "スキップ",
      ko: "스킵",
    },
    wechatAgentBatchFailed: {
      "zh-CN": "失败",
      "zh-TW": "失敗",
      en: "Failed",
      ja: "失敗",
      ko: "실패",
    },
    wechatAgentBatchSubmittedUrl: {
      "zh-CN": "链接入队",
      "zh-TW": "連結入隊",
      en: "URL ingest",
      ja: "URL投入",
      ko: "URL 수집",
    },
    wechatAgentBatchSubmittedOcr: {
      "zh-CN": "OCR 补录",
      "zh-TW": "OCR 補錄",
      en: "OCR Recovery",
      ja: "OCRフォールバック",
      ko: "OCR 폴백",
    },
    wechatAgentBatchUrlFirstShare: {
      "zh-CN": "URL-first 占比",
      "zh-TW": "URL-first 佔比",
      en: "URL-first share",
      ja: "URL-first 比率",
      ko: "URL-first 비중",
    },
    wechatAgentBatchOcrShare: {
      "zh-CN": "OCR 占比",
      "zh-TW": "OCR 佔比",
      en: "OCR share",
      ja: "OCR 比率",
      ko: "OCR 비중",
    },
    wechatAgentBatchDuplicateEscape: {
      "zh-CN": "重复脱困",
      "zh-TW": "重複脫困",
      en: "Duplicate escapes",
      ja: "重複脱出",
      ko: "중복 탈출",
    },
    wechatAgentBatchRouteBackoff: {
      "zh-CN": "Route 回退",
      "zh-TW": "Route 回退",
      en: "Route backoff",
      ja: "Route バックオフ",
      ko: "Route 백오프",
    },
    wechatAgentBatchHardEscape: {
      "zh-CN": "强制脱困",
      "zh-TW": "強制脫困",
      en: "Hard escapes",
      ja: "強制脱出",
      ko: "강제 탈출",
    },
    wechatAgentBatchSubmenuTrap: {
      "zh-CN": "二级入口陷阱",
      "zh-TW": "二級入口陷阱",
      en: "Submenu traps",
      ja: "二階層トラップ",
      ko: "하위 메뉴 함정",
    },
    wechatAgentBatchRouteBreaker: {
      "zh-CN": "Route 熔断",
      "zh-TW": "Route 熔斷",
      en: "Route breaker",
      ja: "Route ブレーカー",
      ko: "Route 차단",
    },
    wechatAgentBatchRecoveries: {
      "zh-CN": "恢复动作",
      "zh-TW": "恢復動作",
      en: "Recoveries",
      ja: "復帰アクション",
      ko: "복구 동작",
    },
    wechatAgentBatchUrlOnlySkips: {
      "zh-CN": "URL-only 跳过",
      "zh-TW": "URL-only 跳過",
      en: "URL-only skips",
      ja: "URL-only スキップ",
      ko: "URL-only 스킵",
    },
    wechatAgentBatchPreviewLoops: {
      "zh-CN": "同文命中",
      "zh-TW": "同文命中",
      en: "Same-article hits",
      ja: "同記事ヒット",
      ko: "동일 글 반복",
    },
    wechatAgentBatchAccessibilityHits: {
      "zh-CN": "AX 命中",
      "zh-TW": "AX 命中",
      en: "AX hits",
      ja: "AX ヒット",
      ko: "AX 적중",
    },
    wechatAgentBatchTemplateHits: {
      "zh-CN": "模板命中",
      "zh-TW": "模板命中",
      en: "Template hits",
      ja: "テンプレートヒット",
      ko: "템플릿 적중",
    },
    wechatAgentBatchPerceptualDedup: {
      "zh-CN": "感知去重",
      "zh-TW": "感知去重",
      en: "Perceptual dedup",
      ja: "知覚重複除外",
      ko: "인지 중복제거",
    },
    wechatAgentBatchMessage: {
      "zh-CN": "最近状态",
      "zh-TW": "最近狀態",
      en: "Latest status",
      ja: "最新状態",
      ko: "최근 상태",
    },
    wechatAgentBatchItemsTitle: {
      "zh-CN": "本轮新增卡片",
      "zh-TW": "本輪新增卡片",
      en: "New Cards in This Run",
      ja: "今回の新規カード",
      ko: "이번 신규 카드",
    },
    wechatAgentBatchItemsHint: {
      "zh-CN": "与专注总结使用同一组新增卡片，可直接打开详情或回到总结页继续筛选。",
      "zh-TW": "與專注總結使用同一組新增卡片，可直接打開詳情或回到總結頁繼續篩選。",
      en: "This uses the same new-card set as Focus Summary. Open detail directly or continue filtering there.",
      ja: "Session Summary と同じ新規カード群です。詳細を開くか、Summary で続けて絞り込めます。",
      ko: "Session Summary와 같은 신규 카드 묶음입니다. 바로 상세를 열거나 Summary에서 계속 필터링할 수 있습니다.",
    },
    wechatAgentBatchOpenSummary: {
      "zh-CN": "回到总结页筛选",
      "zh-TW": "回到總結頁篩選",
      en: "Open Summary Filters",
      ja: "Summary で絞り込む",
      ko: "Summary에서 필터링",
    },
    wechatAgentBatchOpenItem: {
      "zh-CN": "打开详情",
      "zh-TW": "打開詳情",
      en: "Open Detail",
      ja: "詳細を開く",
      ko: "상세 열기",
    },
    untitled: {
      "zh-CN": "未命名内容",
      "zh-TW": "未命名內容",
      en: "Untitled item",
      ja: "無題コンテンツ",
      ko: "제목 없음",
    },
    unknownSource: {
      "zh-CN": "未知来源",
      "zh-TW": "未知來源",
      en: "Unknown source",
      ja: "不明なソース",
      ko: "알 수 없는 출처",
    },
    wechatAgentProcessedHashes: {
      "zh-CN": "已去重哈希数",
      "zh-TW": "已去重雜湊數",
      en: "Dedup Hashes",
      ja: "重複除外ハッシュ数",
      ko: "중복제거 해시 수",
    },
    wechatAgentLastCycle: {
      "zh-CN": "最近扫描",
      "zh-TW": "最近掃描",
      en: "Last Cycle",
      ja: "最新スキャン",
      ko: "최근 스캔",
    },
    wechatAgentRunOncePid: {
      "zh-CN": "单轮 PID",
      "zh-TW": "單輪 PID",
      en: "Run-Once PID",
      ja: "単発 PID",
      ko: "단일 실행 PID",
    },
    wechatAgentCycleSubmitted: {
      "zh-CN": "最近提交",
      "zh-TW": "最近提交",
      en: "Last Submitted",
      ja: "直近送信数",
      ko: "최근 제출",
    },
    wechatAgentCycleFailed: {
      "zh-CN": "最近失败",
      "zh-TW": "最近失敗",
      en: "Last Failed",
      ja: "直近失敗数",
      ko: "최근 실패",
    },
    wechatAgentCycleSkippedSeen: {
      "zh-CN": "最近去重跳过",
      "zh-TW": "最近去重跳過",
      en: "Last Dedup Skipped",
      ja: "直近重複スキップ",
      ko: "최근 중복 스킵",
    },
    wechatAgentCycleLowQuality: {
      "zh-CN": "最近低质量跳过",
      "zh-TW": "最近低品質跳過",
      en: "Last Low-Quality Skipped",
      ja: "直近低品質スキップ",
      ko: "최근 저품질 스킵",
    },
    wechatAgentCycleError: {
      "zh-CN": "最近错误",
      "zh-TW": "最近錯誤",
      en: "Last Error",
      ja: "直近エラー",
      ko: "최근 오류",
    },
    wechatAgentDedupTitle: {
      "zh-CN": "去重状态",
      "zh-TW": "去重狀態",
      en: "Dedup State",
      ja: "重複除外状態",
      ko: "중복 제거 상태",
    },
    wechatAgentDedupRuns: {
      "zh-CN": "历史轮次",
      "zh-TW": "歷史輪次",
      en: "Run History",
      ja: "実行履歴",
      ko: "실행 이력",
    },
    wechatAgentDedupLastRun: {
      "zh-CN": "最近完成",
      "zh-TW": "最近完成",
      en: "Last Finished",
      ja: "直近完了",
      ko: "최근 완료",
    },
    wechatAgentDedupReset: {
      "zh-CN": "重置去重",
      "zh-TW": "重置去重",
      en: "Reset Dedup",
      ja: "重複除外をリセット",
      ko: "중복 제거 초기화",
    },
    wechatAgentDedupResetHard: {
      "zh-CN": "清空去重+历史",
      "zh-TW": "清空去重+歷史",
      en: "Clear Dedup + Runs",
      ja: "重複除外+履歴を削除",
      ko: "중복 제거+이력 삭제",
    },
    wechatAgentDedupResetHint: {
      "zh-CN": "用于重新验证最新公众号流，避免历史哈希把新一轮测试全部判成已见。",
      "zh-TW": "用於重新驗證最新公眾號流，避免歷史雜湊把新一輪測試全部判成已見。",
      en: "Use this before a fresh regression run so historical hashes do not mark the whole batch as seen.",
      ja: "再回帰前に使用し、過去ハッシュで全件既読判定されるのを防ぎます。",
      ko: "새 회귀 전에 사용해 과거 해시로 전체가 이미 본 항목 처리되는 것을 막습니다.",
    },
    wechatAgentBatchLive: {
      "zh-CN": "段内实时进度",
      "zh-TW": "段內即時進度",
      en: "Live In-Segment Progress",
      ja: "セグメント内リアルタイム進捗",
      ko: "세그먼트 내 실시간 진행",
    },
    wechatAgentBatchLiveCheckpoint: {
      "zh-CN": "最近检查点",
      "zh-TW": "最近檢查點",
      en: "Latest Checkpoint",
      ja: "最新チェックポイント",
      ko: "최근 체크포인트",
    },
    wechatAgentConfigTitle: {
      "zh-CN": "微信采集坐标配置",
      "zh-TW": "微信採集座標配置",
      en: "WeChat Collection Coordinates",
      ja: "WeChat Agent 座標設定",
      ko: "WeChat Agent 좌표 설정",
    },
    wechatAgentConfigSave: {
      "zh-CN": "保存配置",
      "zh-TW": "儲存配置",
      en: "Save Config",
      ja: "設定を保存",
      ko: "설정 저장",
    },
    wechatAgentConfigRows: {
      "zh-CN": "每批行数",
      "zh-TW": "每批行數",
      en: "Rows/Batch",
      ja: "行数/バッチ",
      ko: "배치당 행수",
    },
    wechatAgentConfigBatches: {
      "zh-CN": "每轮批次",
      "zh-TW": "每輪批次",
      en: "Batches/Cycle",
      ja: "バッチ/サイクル",
      ko: "사이클당 배치",
    },
    wechatAgentConfigRowHeight: {
      "zh-CN": "行高",
      "zh-TW": "行高",
      en: "Row Height",
      ja: "行の高さ",
      ko: "행 높이",
    },
    wechatAgentConfigListOrigin: {
      "zh-CN": "列表原点 (x,y)",
      "zh-TW": "列表原點 (x,y)",
      en: "List Origin (x,y)",
      ja: "一覧原点 (x,y)",
      ko: "목록 원점 (x,y)",
    },
    wechatAgentConfigCapture: {
      "zh-CN": "截图区域 (x,y,w,h)",
      "zh-TW": "截圖區域 (x,y,w,h)",
      en: "Capture Rect (x,y,w,h)",
      ja: "キャプチャ領域 (x,y,w,h)",
      ko: "캡처 영역 (x,y,w,h)",
    },
    wechatAgentConfigProfile: {
      "zh-CN": "链接提取策略",
      "zh-TW": "連結提取策略",
      en: "Link Extraction Profile",
      ja: "リンク抽出プロファイル",
      ko: "링크 추출 프로필",
    },
    wechatAgentConfigProfileHint: {
      "zh-CN": "auto 会先试内置热点模板；manual 仅使用下方自定义热点和菜单偏移。",
      "zh-TW": "auto 會先試內建熱點模板；manual 僅使用下方自訂熱點與選單偏移。",
      en: "auto tries built-in hotspot templates first; manual uses only the custom hotspot and menu offsets below.",
      ja: "auto は内蔵ホットスポットを優先し、manual は下のカスタム点だけを使います。",
      ko: "auto는 내장 핫스팟 템플릿을 우선 사용하고, manual은 아래 사용자 정의 점만 사용합니다.",
    },
    wechatAgentConfigProfileAuto: {
      "zh-CN": "自动",
      "zh-TW": "自動",
      en: "Auto",
      ja: "自動",
      ko: "자동",
    },
    wechatAgentConfigProfileCompact: {
      "zh-CN": "紧凑窗口",
      "zh-TW": "緊湊視窗",
      en: "Compact Window",
      ja: "コンパクト",
      ko: "콤팩트 창",
    },
    wechatAgentConfigProfileStandard: {
      "zh-CN": "标准窗口",
      "zh-TW": "標準視窗",
      en: "Standard Window",
      ja: "標準",
      ko: "표준 창",
    },
    wechatAgentConfigProfileWide: {
      "zh-CN": "宽窗口",
      "zh-TW": "寬視窗",
      en: "Wide Window",
      ja: "ワイド",
      ko: "와이드 창",
    },
    wechatAgentConfigProfileManual: {
      "zh-CN": "仅自定义热点",
      "zh-TW": "僅自訂熱點",
      en: "Manual Hotspots Only",
      ja: "カスタムのみ",
      ko: "사용자 정의만",
    },
    wechatAgentConfigHotspots: {
      "zh-CN": "分享热点 (右边距:上边距)",
      "zh-TW": "分享熱點 (右邊距:上邊距)",
      en: "Share Hotspots (right:top)",
      ja: "共有ホットスポット (右余白:上余白)",
      ko: "공유 핫스팟 (오른쪽:위)",
    },
    wechatAgentConfigMenuOffsets: {
      "zh-CN": "菜单候选偏移 (dx:dy)",
      "zh-TW": "選單候選偏移 (dx:dy)",
      en: "Menu Offsets (dx:dy)",
      ja: "メニュー候補オフセット (dx:dy)",
      ko: "메뉴 후보 오프셋 (dx:dy)",
    },
    wechatAgentConfigHotspotsHint: {
      "zh-CN": "文章页右上角分享/打开浏览器热点，多个点用逗号分隔。",
      "zh-TW": "文章頁右上角分享/開啟瀏覽器熱點，多個點用逗號分隔。",
      en: "Article-page share/open-browser hotspots. Separate multiple points with commas.",
      ja: "記事右上の共有/ブラウザ起動ホットスポット。複数点はカンマ区切り。",
      ko: "기사 우측 상단 공유/브라우저 열기 핫스팟. 여러 점은 쉼표로 구분.",
    },
    wechatAgentConfigMenuHint: {
      "zh-CN": "相对分享热点的菜单点击候选，用于复制链接/浏览器打开。",
      "zh-TW": "相對分享熱點的選單候選，用於複製連結/瀏覽器開啟。",
      en: "Relative menu click candidates for copy-link/open-browser.",
      ja: "共有点からの相対メニュー候補。リンクコピー/ブラウザ起動用。",
      ko: "공유 지점 기준 상대 메뉴 후보. 링크 복사/브라우저 열기용.",
    },
    wechatAgentConfigInterval: {
      "zh-CN": "循环间隔 (秒)",
      "zh-TW": "循環間隔 (秒)",
      en: "Loop Interval (sec)",
      ja: "ループ間隔 (秒)",
      ko: "루프 간격 (초)",
    },
    wechatAgentConfigMinFileSize: {
      "zh-CN": "最小截图体积 (KB)",
      "zh-TW": "最小截圖大小 (KB)",
      en: "Min Capture Size (KB)",
      ja: "最小キャプチャサイズ (KB)",
      ko: "최소 캡처 크기 (KB)",
    },
    wechatAgentPreviewCapture: {
      "zh-CN": "截图校准预览",
      "zh-TW": "截圖校準預覽",
      en: "Capture Preview",
      ja: "キャプチャ校正プレビュー",
      ko: "캡처 보정 미리보기",
    },
    wechatAgentPreviewOCR: {
      "zh-CN": "OCR 质量预览",
      "zh-TW": "OCR 品質預覽",
      en: "OCR Preview",
      ja: "OCR 品質プレビュー",
      ko: "OCR 품질 미리보기",
    },
    wechatAgentPreviewImage: {
      "zh-CN": "预览截图",
      "zh-TW": "預覽截圖",
      en: "Preview Image",
      ja: "プレビュー画像",
      ko: "미리보기 이미지",
    },
    wechatAgentPreviewSize: {
      "zh-CN": "截图体积",
      "zh-TW": "截圖大小",
      en: "Capture Size",
      ja: "キャプチャサイズ",
      ko: "캡처 크기",
    },
    wechatAgentPreviewOCRTitle: {
      "zh-CN": "OCR 识别预览",
      "zh-TW": "OCR 識別預覽",
      en: "OCR Result",
      ja: "OCR 結果",
      ko: "OCR 결과",
    },
    wechatAgentPreviewOCRQuality: {
      "zh-CN": "质量判定",
      "zh-TW": "品質判定",
      en: "Quality",
      ja: "品質判定",
      ko: "품질 판정",
    },
    wechatAgentPreviewOCRQualityOK: {
      "zh-CN": "通过",
      "zh-TW": "通過",
      en: "Pass",
      ja: "合格",
      ko: "통과",
    },
    wechatAgentPreviewOCRQualityBad: {
      "zh-CN": "不通过",
      "zh-TW": "不通過",
      en: "Fail",
      ja: "不合格",
      ko: "실패",
    },
    wechatAgentPreviewOCRReason: {
      "zh-CN": "原因",
      "zh-TW": "原因",
      en: "Reason",
      ja: "理由",
      ko: "사유",
    },
    wechatAgentPreviewOCRProvider: {
      "zh-CN": "OCR 提供方",
      "zh-TW": "OCR 來源",
      en: "Provider",
      ja: "OCR プロバイダ",
      ko: "OCR 제공자",
    },
    wechatAgentPreviewOCRBody: {
      "zh-CN": "正文预览",
      "zh-TW": "正文預覽",
      en: "Body Preview",
      ja: "本文プレビュー",
      ko: "본문 미리보기",
    },
    wechatAgentPreviewOCRKeywords: {
      "zh-CN": "关键词",
      "zh-TW": "關鍵詞",
      en: "Keywords",
      ja: "キーワード",
      ko: "키워드",
    },
    wechatAgentHealthCheck: {
      "zh-CN": "健康检查",
      "zh-TW": "健康檢查",
      en: "Health Check",
      ja: "ヘルスチェック",
      ko: "상태 점검",
    },
    wechatAgentSelfHeal: {
      "zh-CN": "一键修复",
      "zh-TW": "一鍵修復",
      en: "Self Heal",
      ja: "自動修復",
      ko: "자동 복구",
    },
    wechatAgentHealthHealthy: {
      "zh-CN": "健康",
      "zh-TW": "健康",
      en: "Healthy",
      ja: "正常",
      ko: "정상",
    },
    wechatAgentHealthUnhealthy: {
      "zh-CN": "异常",
      "zh-TW": "異常",
      en: "Unhealthy",
      ja: "異常",
      ko: "이상",
    },
    wechatAgentHealthReasons: {
      "zh-CN": "异常原因",
      "zh-TW": "異常原因",
      en: "Reasons",
      ja: "理由",
      ko: "사유",
    },
    wechatAgentHealthCheckedAt: {
      "zh-CN": "检查时间",
      "zh-TW": "檢查時間",
      en: "Checked At",
      ja: "確認時刻",
      ko: "확인 시각",
    },
    wechatAgentConfigHealthStale: {
      "zh-CN": "健康阈值 (分钟)",
      "zh-TW": "健康閾值 (分鐘)",
      en: "Health Stale (min)",
      ja: "ヘルス閾値 (分)",
      ko: "건강 임계값 (분)",
    },
    refresh: {
      "zh-CN": "刷新状态",
      "zh-TW": "刷新狀態",
      en: "Refresh",
      ja: "更新",
      ko: "새로고침",
    },
    flushPending: {
      "zh-CN": "补偿 Pending",
      "zh-TW": "補償 Pending",
      en: "Flush Pending",
      ja: "Pending補完",
      ko: "Pending 보정",
    },
    retryFailed: {
      "zh-CN": "重试 Failed",
      "zh-TW": "重試 Failed",
      en: "Retry Failed",
      ja: "Failed再試行",
      ko: "Failed 재시도",
    },
    generateDaily: {
      "zh-CN": "生成日报 Markdown",
      "zh-TW": "生成日報 Markdown",
      en: "Generate Daily Markdown",
      ja: "日次Markdown生成",
      ko: "일일 Markdown 생성",
    },
    copy: {
      "zh-CN": "复制 Markdown",
      "zh-TW": "複製 Markdown",
      en: "Copy Markdown",
      ja: "Markdownをコピー",
      ko: "Markdown 복사",
    },
    statusTitle: {
      "zh-CN": "24h 采集状态",
      "zh-TW": "24h 採集狀態",
      en: "24h Collector Status",
      ja: "24時間ステータス",
      ko: "24시간 수집 상태",
    },
    failedTitle: {
      "zh-CN": "失败列表",
      "zh-TW": "失敗列表",
      en: "Failed Items",
      ja: "失敗一覧",
      ko: "실패 목록",
    },
    failedEmpty: {
      "zh-CN": "当前没有失败项。",
      "zh-TW": "目前沒有失敗項。",
      en: "No failed items.",
      ja: "失敗項目はありません。",
      ko: "실패 항목이 없습니다.",
    },
    dailyTitle: {
      "zh-CN": "日报摘要",
      "zh-TW": "日報摘要",
      en: "Daily Summary",
      ja: "日次サマリー",
      ko: "일일 요약",
    },
    markdownPlaceholder: {
      "zh-CN": "点击“生成日报 Markdown”后显示导出内容。",
      "zh-TW": "點擊「生成日報 Markdown」後顯示導出內容。",
      en: "Generated Markdown will appear here.",
      ja: "生成したMarkdownがここに表示されます。",
      ko: "생성된 Markdown이 여기에 표시됩니다.",
    },
    total: {
      "zh-CN": "总数",
      "zh-TW": "總數",
      en: "Total",
      ja: "合計",
      ko: "총계",
    },
    ready: {
      "zh-CN": "已完成",
      "zh-TW": "已完成",
      en: "Ready",
      ja: "完了",
      ko: "완료",
    },
    pending: {
      "zh-CN": "处理中",
      "zh-TW": "處理中",
      en: "Pending",
      ja: "処理中",
      ko: "처리중",
    },
    failed: {
      "zh-CN": "失败",
      "zh-TW": "失敗",
      en: "Failed",
      ja: "失敗",
      ko: "실패",
    },
    ocr: {
      "zh-CN": "OCR 入库",
      "zh-TW": "OCR 入庫",
      en: "OCR Ingest",
      ja: "OCR取り込み",
      ko: "OCR 수집",
    },
    messageCopied: {
      "zh-CN": "Markdown 已复制到剪贴板。",
      "zh-TW": "Markdown 已複製到剪貼簿。",
      en: "Markdown copied to clipboard.",
      ja: "Markdownをクリップボードにコピーしました。",
      ko: "Markdown이 클립보드에 복사되었습니다.",
    },
    source: {
      "zh-CN": "来源",
      "zh-TW": "來源",
      en: "Source",
      ja: "ソース",
      ko: "출처",
    },
    titleCol: {
      "zh-CN": "标题",
      "zh-TW": "標題",
      en: "Title",
      ja: "タイトル",
      ko: "제목",
    },
    error: {
      "zh-CN": "错误",
      "zh-TW": "錯誤",
      en: "Error",
      ja: "エラー",
      ko: "오류",
    },
};

export function localText(language: AppLanguage, key: string): string {
  return pickText(language, COLLECTOR_OPS_COPY[key] || {}, key);
}
