import type { AppLanguage } from "@/lib/preferences";
import { pickText } from "@/components/settings/collector-ops-panel-utils";

const COLLECTOR_OPS_COPY: Record<string, Partial<Record<AppLanguage, string>>> = {
    title: {
      "zh-CN": "采集设置",
      "zh-TW": "採集設定",
      en: "Collection Settings",
      ja: "Collector 運用パネル",
      ko: "Collector 운영 패널",
    },
    description: {
      "zh-CN": "管理采集、重试和日报。",
      "zh-TW": "管理採集、重試和日報。",
      en: "Manage collection, retries, and daily summaries.",
      ja: "収集、再試行、日次サマリーを管理します。",
      ko: "수집, 재시도, 일일 요약을 관리합니다.",
    },
    daemonTitle: {
      "zh-CN": "自动采集",
      "zh-TW": "自動採集",
      en: "Auto collection",
      ja: "収集デーモン",
      ko: "수집 데몬",
    },
    daemonRunning: {
      "zh-CN": "运行中",
      "zh-TW": "運行中",
      en: "Running",
      ja: "稼働中",
      ko: "실행 중",
    },
    daemonStopped: {
      "zh-CN": "已停止",
      "zh-TW": "已停止",
      en: "Stopped",
      ja: "停止中",
      ko: "중지됨",
    },
    startDaemon: {
      "zh-CN": "启动采集器",
      "zh-TW": "啟動採集器",
      en: "Start",
      ja: "開始",
      ko: "시작",
    },
    stopDaemon: {
      "zh-CN": "停止采集器",
      "zh-TW": "停止採集器",
      en: "Stop",
      ja: "停止",
      ko: "중지",
    },
    runOnce: {
      "zh-CN": "执行单轮采集",
      "zh-TW": "執行單輪採集",
      en: "Run Once",
      ja: "単発実行",
      ko: "1회 실행",
    },
    daemonPid: {
      "zh-CN": "运行编号",
      "zh-TW": "運行編號",
      en: "PID",
      ja: "PID",
      ko: "PID",
    },
    daemonUptime: {
      "zh-CN": "运行时长",
      "zh-TW": "運行時長",
      en: "Uptime",
      ja: "稼働時間",
      ko: "가동 시간",
    },
    daemonSources: {
      "zh-CN": "监控链接",
      "zh-TW": "監控連結",
      en: "Source URLs",
      ja: "ソースURL数",
      ko: "소스 URL 수",
    },
    daemonLastReport: {
      "zh-CN": "最近报告",
      "zh-TW": "最近報告",
      en: "Latest report",
      ja: "最新レポート",
      ko: "최근 리포트",
    },
    daemonLastDaily: {
      "zh-CN": "最近日报",
      "zh-TW": "最近日報",
      en: "Latest daily summary",
      ja: "最新日次",
      ko: "최근 일일 요약",
    },
    daemonLastRun: {
      "zh-CN": "最近一轮",
      "zh-TW": "最近一輪",
      en: "Latest run",
      ja: "直近の実行",
      ko: "최근 실행",
    },
    daemonSubmitMode: {
      "zh-CN": "处理方式",
      "zh-TW": "處理方式",
      en: "Submit mode",
      ja: "送信モード",
      ko: "제출 모드",
    },
    daemonDiscovered: {
      "zh-CN": "发现文章",
      "zh-TW": "發現文章",
      en: "Discovered",
      ja: "検出記事",
      ko: "발견 기사",
    },
    daemonCollected: {
      "zh-CN": "提交总数",
      "zh-TW": "提交總數",
      en: "Collected",
      ja: "送信総数",
      ko: "제출 합계",
    },
    daemonPluginCount: {
      "zh-CN": "浏览器采集",
      "zh-TW": "瀏覽器採集",
      en: "Browser collection",
      ja: "Browser plugin",
      ko: "Browser plugin",
    },
    daemonUrlFallbackCount: {
      "zh-CN": "链接补录",
      "zh-TW": "連結補錄",
      en: "URL recovery",
      ja: "URL recovery",
      ko: "URL recovery",
    },
    daemonFailedCount: {
      "zh-CN": "失败数",
      "zh-TW": "失敗數",
      en: "Failed",
      ja: "失敗数",
      ko: "실패 수",
    },
    daemonCoverageRate: {
      "zh-CN": "处理覆盖",
      "zh-TW": "處理覆蓋",
      en: "Coverage",
      ja: "処理カバレッジ",
      ko: "처리 커버리지",
    },
    daemonBodyRate: {
      "zh-CN": "正文获取",
      "zh-TW": "正文取得",
      en: "Body capture",
      ja: "本文取得率",
      ko: "본문 적중률",
    },
    daemonHandledCount: {
      "zh-CN": "已处理/跳过",
      "zh-TW": "已處理/跳過",
      en: "Handled / skipped",
      ja: "処理/スキップ済み",
      ko: "처리/건너뜀",
    },
    daemonRecentRows: {
      "zh-CN": "最近采集结果",
      "zh-TW": "最近採集結果",
      en: "Recent results",
      ja: "直近 batch 結果",
      ko: "최근 batch 결과",
    },
    daemonSourceHealth: {
      "zh-CN": "来源健康度",
      "zh-TW": "來源健康度",
      en: "Source health",
      ja: "ソース健全性",
      ko: "소스 상태",
    },
    daemonLogTail: {
      "zh-CN": "运行记录",
      "zh-TW": "執行記錄",
      en: "Run records",
      ja: "直近ログ",
      ko: "최근 로그",
    },
    daemonOutput: {
      "zh-CN": "执行记录",
      "zh-TW": "執行記錄",
      en: "Run log",
      ja: "実行出力",
      ko: "실행 출력",
    },
    wechatAgentTitle: {
      "zh-CN": "微信文章自动采集",
      "zh-TW": "微信文章自動採集",
      en: "WeChat article collection",
      ja: "WeChat PC 全自動 Agent",
      ko: "WeChat PC 풀오토 Agent",
    },
    wechatAgentHint: {
      "zh-CN": "自动读取公众号文章链接并加入收件箱；补录能力仅在明确开启后使用。",
      "zh-TW": "自動讀取公眾號文章連結並加入收件箱；補錄能力僅在明確開啟後使用。",
      en: "Reads WeChat article links and adds them to Inbox; recovery is only used when enabled.",
      ja: "公開記事リンクを自動で読み取り、Inbox に追加します。補完機能は有効化した場合のみ使います。",
      ko: "공개 글 링크를 자동으로 읽어 Inbox에 추가합니다. 보완 기능은 켠 경우에만 사용합니다.",
    },
    wechatAgentStart: {
      "zh-CN": "启动微信采集",
      "zh-TW": "啟動微信採集",
      en: "Start WeChat Collection",
      ja: "WeChat Agent 開始",
      ko: "WeChat Agent 시작",
    },
    wechatAgentStop: {
      "zh-CN": "停止微信采集",
      "zh-TW": "停止微信採集",
      en: "Stop WeChat Collection",
      ja: "WeChat Agent 停止",
      ko: "WeChat Agent 중지",
    },
    wechatAgentRunOnce: {
      "zh-CN": "单轮扫描",
      "zh-TW": "單輪掃描",
      en: "Run Single Cycle",
      ja: "単発スキャン",
      ko: "1회 스캔",
    },
    wechatAgentRunBatch: {
      "zh-CN": "分段扫描 18 篇",
      "zh-TW": "分段掃描 18 篇",
      en: "Segmented Scan 18",
      ja: "分割スキャン 18",
      ko: "분할 스캔 18",
    },
    wechatAgentBatchTitle: {
      "zh-CN": "最近一轮采集",
      "zh-TW": "最近一輪採集",
      en: "Latest collection",
      ja: "直近の分割バッチ",
      ko: "최근 분할 배치",
    },
    wechatAgentBatchProgress: {
      "zh-CN": "进度",
      "zh-TW": "進度",
      en: "Progress",
      ja: "進捗",
      ko: "진행률",
    },
    wechatAgentBatchSubmittedNew: {
      "zh-CN": "真正新增",
      "zh-TW": "真正新增",
      en: "New",
      ja: "新規",
      ko: "신규",
    },
    wechatAgentBatchDedup: {
      "zh-CN": "历史去重",
      "zh-TW": "歷史去重",
      en: "Deduplicated",
      ja: "既存重複",
      ko: "중복",
    },
    wechatAgentBatchSeen: {
      "zh-CN": "已跳过",
      "zh-TW": "已跳過",
      en: "Skipped",
      ja: "スキップ",
      ko: "스킵",
    },
    wechatAgentBatchFailed: {
      "zh-CN": "失败",
      "zh-TW": "失敗",
      en: "Failed",
      ja: "失敗",
      ko: "실패",
    },
    wechatAgentBatchSubmittedUrl: {
      "zh-CN": "链接导入",
      "zh-TW": "連結導入",
      en: "Link import",
      ja: "リンク取り込み",
      ko: "링크 가져오기",
    },
    wechatAgentBatchSubmittedOcr: {
      "zh-CN": "内容补录",
      "zh-TW": "內容補錄",
      en: "Content recovery",
      ja: "内容補完",
      ko: "내용 보완",
    },
    wechatAgentBatchUrlFirstShare: {
      "zh-CN": "链接优先率",
      "zh-TW": "連結優先率",
      en: "Link-first share",
      ja: "リンク優先率",
      ko: "링크 우선율",
    },
    wechatAgentBatchOcrShare: {
      "zh-CN": "补录占比",
      "zh-TW": "補錄佔比",
      en: "Recovery share",
      ja: "補完比率",
      ko: "보완 비율",
    },
    wechatAgentBatchDuplicateEscape: {
      "zh-CN": "重复处理",
      "zh-TW": "重複處理",
      en: "Duplicate handling",
      ja: "重複脱出",
      ko: "중복 탈출",
    },
    wechatAgentBatchRouteBackoff: {
      "zh-CN": "降级处理",
      "zh-TW": "降級處理",
      en: "Recovery handling",
      ja: "フォールバック処理",
      ko: "대체 처리",
    },
    wechatAgentBatchHardEscape: {
      "zh-CN": "自动恢复",
      "zh-TW": "自動恢復",
      en: "Auto recovery",
      ja: "自動復帰",
      ko: "자동 복구",
    },
    wechatAgentBatchSubmenuTrap: {
      "zh-CN": "入口切换",
      "zh-TW": "入口切換",
      en: "Entry switching",
      ja: "入口切替",
      ko: "진입 전환",
    },
    wechatAgentBatchRouteBreaker: {
      "zh-CN": "采集保护",
      "zh-TW": "採集保護",
      en: "Collection guard",
      ja: "収集ガード",
      ko: "수집 보호",
    },
    wechatAgentBatchRecoveries: {
      "zh-CN": "恢复次数",
      "zh-TW": "恢復次數",
      en: "Recoveries",
      ja: "復帰回数",
      ko: "복구 횟수",
    },
    wechatAgentBatchUrlOnlySkips: {
      "zh-CN": "仅链接跳过",
      "zh-TW": "僅連結跳過",
      en: "Link-only skips",
      ja: "リンクのみスキップ",
      ko: "링크만 건너뜀",
    },
    wechatAgentBatchPreviewLoops: {
      "zh-CN": "重复内容",
      "zh-TW": "重複內容",
      en: "Repeated content",
      ja: "同記事ヒット",
      ko: "동일 글 반복",
    },
    wechatAgentBatchAccessibilityHits: {
      "zh-CN": "自动操作",
      "zh-TW": "自動操作",
      en: "Auto actions",
      ja: "自動操作",
      ko: "자동 작업",
    },
    wechatAgentBatchTemplateHits: {
      "zh-CN": "模板识别",
      "zh-TW": "模板識別",
      en: "Template matches",
      ja: "テンプレートヒット",
      ko: "템플릿 적중",
    },
    wechatAgentBatchPerceptualDedup: {
      "zh-CN": "感知去重",
      "zh-TW": "感知去重",
      en: "Perceptual dedup",
      ja: "知覚重複除外",
      ko: "인지 중복제거",
    },
    wechatAgentBatchMessage: {
      "zh-CN": "最近状态",
      "zh-TW": "最近狀態",
      en: "Latest status",
      ja: "最新状態",
      ko: "최근 상태",
    },
    wechatAgentBatchItemsTitle: {
      "zh-CN": "本轮新增卡片",
      "zh-TW": "本輪新增卡片",
      en: "New Cards in This Run",
      ja: "今回の新規カード",
      ko: "이번 신규 카드",
    },
    wechatAgentBatchItemsHint: {
      "zh-CN": "与专注总结使用同一组新增卡片，可直接打开详情或回到总结页继续筛选。",
      "zh-TW": "與專注總結使用同一組新增卡片，可直接打開詳情或回到總結頁繼續篩選。",
      en: "This uses the same new-card set as Focus Summary. Open detail directly or continue filtering there.",
      ja: "Session Summary と同じ新規カード群です。詳細を開くか、Summary で続けて絞り込めます。",
      ko: "Session Summary와 같은 신규 카드 묶음입니다. 바로 상세를 열거나 Summary에서 계속 필터링할 수 있습니다.",
    },
    wechatAgentBatchOpenSummary: {
      "zh-CN": "回到总结页筛选",
      "zh-TW": "回到總結頁篩選",
      en: "Open Summary Filters",
      ja: "Summary で絞り込む",
      ko: "Summary에서 필터링",
    },
    wechatAgentBatchOpenItem: {
      "zh-CN": "打开详情",
      "zh-TW": "打開詳情",
      en: "Open Detail",
      ja: "詳細を開く",
      ko: "상세 열기",
    },
    untitled: {
      "zh-CN": "未命名内容",
      "zh-TW": "未命名內容",
      en: "Untitled item",
      ja: "無題コンテンツ",
      ko: "제목 없음",
    },
    unknownSource: {
      "zh-CN": "未知来源",
      "zh-TW": "未知來源",
      en: "Unknown source",
      ja: "不明なソース",
      ko: "알 수 없는 출처",
    },
    wechatAgentProcessedHashes: {
      "zh-CN": "已去重记录",
      "zh-TW": "已去重記錄",
      en: "Deduplicated records",
      ja: "重複除外ハッシュ数",
      ko: "중복제거 해시 수",
    },
    wechatAgentLastCycle: {
      "zh-CN": "最近扫描",
      "zh-TW": "最近掃描",
      en: "Last Cycle",
      ja: "最新スキャン",
      ko: "최근 스캔",
    },
    wechatAgentRunOncePid: {
      "zh-CN": "单轮编号",
      "zh-TW": "單輪編號",
      en: "Run ID",
      ja: "単発 PID",
      ko: "단일 실행 PID",
    },
    wechatAgentCycleSubmitted: {
      "zh-CN": "最近提交",
      "zh-TW": "最近提交",
      en: "Last Submitted",
      ja: "直近送信数",
      ko: "최근 제출",
    },
    wechatAgentCycleFailed: {
      "zh-CN": "最近失败",
      "zh-TW": "最近失敗",
      en: "Last Failed",
      ja: "直近失敗数",
      ko: "최근 실패",
    },
    wechatAgentCycleSkippedSeen: {
      "zh-CN": "最近已见",
      "zh-TW": "最近已見",
      en: "Recently seen",
      ja: "直近重複スキップ",
      ko: "최근 중복 스킵",
    },
    wechatAgentCycleLowQuality: {
      "zh-CN": "最近未采用",
      "zh-TW": "最近未採用",
      en: "Recently skipped",
      ja: "直近低品質スキップ",
      ko: "최근 저품질 스킵",
    },
    wechatAgentCycleError: {
      "zh-CN": "最近错误",
      "zh-TW": "最近錯誤",
      en: "Last Error",
      ja: "直近エラー",
      ko: "최근 오류",
    },
    wechatAgentDedupTitle: {
      "zh-CN": "去重状态",
      "zh-TW": "去重狀態",
      en: "Dedup State",
      ja: "重複除外状態",
      ko: "중복 제거 상태",
    },
    wechatAgentDedupRuns: {
      "zh-CN": "历史轮次",
      "zh-TW": "歷史輪次",
      en: "Run History",
      ja: "実行履歴",
      ko: "실행 이력",
    },
    wechatAgentDedupLastRun: {
      "zh-CN": "最近完成",
      "zh-TW": "最近完成",
      en: "Last Finished",
      ja: "直近完了",
      ko: "최근 완료",
    },
    wechatAgentDedupReset: {
      "zh-CN": "重置去重",
      "zh-TW": "重置去重",
      en: "Reset Dedup",
      ja: "重複除外をリセット",
      ko: "중복 제거 초기화",
    },
    wechatAgentDedupResetHard: {
      "zh-CN": "清空去重+历史",
      "zh-TW": "清空去重+歷史",
      en: "Clear Dedup + Runs",
      ja: "重複除外+履歴を削除",
      ko: "중복 제거+이력 삭제",
    },
    wechatAgentDedupResetHint: {
      "zh-CN": "用于重新检查公众号流，避免历史记录影响新一轮导入。",
      "zh-TW": "用於重新檢查公眾號流，避免歷史記錄影響新一輪導入。",
      en: "Use this before rechecking a WeChat feed so prior records do not affect the next import.",
      ja: "再回帰前に使用し、過去ハッシュで全件既読判定されるのを防ぎます。",
      ko: "새 회귀 전에 사용해 과거 해시로 전체가 이미 본 항목 처리되는 것을 막습니다.",
    },
    wechatAgentBatchLive: {
      "zh-CN": "段内实时进度",
      "zh-TW": "段內即時進度",
      en: "Live In-Segment Progress",
      ja: "セグメント内リアルタイム進捗",
      ko: "세그먼트 내 실시간 진행",
    },
    wechatAgentBatchLiveCheckpoint: {
      "zh-CN": "最近检查点",
      "zh-TW": "最近檢查點",
      en: "Latest Checkpoint",
      ja: "最新チェックポイント",
      ko: "최근 체크포인트",
    },
    wechatAgentConfigTitle: {
      "zh-CN": "微信采集坐标配置",
      "zh-TW": "微信採集座標配置",
      en: "WeChat Collection Coordinates",
      ja: "WeChat Agent 座標設定",
      ko: "WeChat Agent 좌표 설정",
    },
    wechatAgentConfigSave: {
      "zh-CN": "保存配置",
      "zh-TW": "儲存配置",
      en: "Save Config",
      ja: "設定を保存",
      ko: "설정 저장",
    },
    wechatAgentConfigRows: {
      "zh-CN": "每批行数",
      "zh-TW": "每批行數",
      en: "Rows per group",
      ja: "行数/バッチ",
      ko: "배치당 행수",
    },
    wechatAgentConfigBatches: {
      "zh-CN": "每轮批次",
      "zh-TW": "每輪批次",
      en: "Groups per run",
      ja: "バッチ/サイクル",
      ko: "사이클당 배치",
    },
    wechatAgentConfigRowHeight: {
      "zh-CN": "行高",
      "zh-TW": "行高",
      en: "Row Height",
      ja: "行の高さ",
      ko: "행 높이",
    },
    wechatAgentConfigListOrigin: {
      "zh-CN": "列表原点 (x,y)",
      "zh-TW": "列表原點 (x,y)",
      en: "List Origin (x,y)",
      ja: "一覧原点 (x,y)",
      ko: "목록 원점 (x,y)",
    },
    wechatAgentConfigCapture: {
      "zh-CN": "截图区域 (x,y,w,h)",
      "zh-TW": "截圖區域 (x,y,w,h)",
      en: "Capture Rect (x,y,w,h)",
      ja: "キャプチャ領域 (x,y,w,h)",
      ko: "캡처 영역 (x,y,w,h)",
    },
    wechatAgentConfigProfile: {
      "zh-CN": "链接提取策略",
      "zh-TW": "連結提取策略",
      en: "Link Extraction Profile",
      ja: "リンク抽出プロファイル",
      ko: "링크 추출 프로필",
    },
    wechatAgentConfigProfileHint: {
      "zh-CN": "自动模式适合大多数窗口；高级模式仅在采集不稳定时调整。",
      "zh-TW": "自動模式適合多數視窗；進階模式僅在採集不穩定時調整。",
      en: "Auto works for most windows; use advanced settings only when collection is unstable.",
      ja: "auto は内蔵ホットスポットを優先し、manual は下のカスタム点だけを使います。",
      ko: "auto는 내장 핫스팟 템플릿을 우선 사용하고, manual은 아래 사용자 정의 점만 사용합니다.",
    },
    wechatAgentConfigProfileAuto: {
      "zh-CN": "自动",
      "zh-TW": "自動",
      en: "Auto",
      ja: "自動",
      ko: "자동",
    },
    wechatAgentConfigProfileCompact: {
      "zh-CN": "紧凑窗口",
      "zh-TW": "緊湊視窗",
      en: "Compact Window",
      ja: "コンパクト",
      ko: "콤팩트 창",
    },
    wechatAgentConfigProfileStandard: {
      "zh-CN": "标准窗口",
      "zh-TW": "標準視窗",
      en: "Standard Window",
      ja: "標準",
      ko: "표준 창",
    },
    wechatAgentConfigProfileWide: {
      "zh-CN": "宽窗口",
      "zh-TW": "寬視窗",
      en: "Wide Window",
      ja: "ワイド",
      ko: "와이드 창",
    },
    wechatAgentConfigProfileManual: {
      "zh-CN": "高级自定义",
      "zh-TW": "進階自訂",
      en: "Advanced custom",
      ja: "カスタムのみ",
      ko: "사용자 정의만",
    },
    wechatAgentConfigHotspots: {
      "zh-CN": "分享位置",
      "zh-TW": "分享位置",
      en: "Share position",
      ja: "共有ホットスポット (右余白:上余白)",
      ko: "공유 핫스팟 (오른쪽:위)",
    },
    wechatAgentConfigMenuOffsets: {
      "zh-CN": "菜单位置",
      "zh-TW": "選單位置",
      en: "Menu position",
      ja: "メニュー候補オフセット (dx:dy)",
      ko: "메뉴 후보 오프셋 (dx:dy)",
    },
    wechatAgentConfigHotspotsHint: {
      "zh-CN": "高级设置。多组位置用逗号分隔。",
      "zh-TW": "進階設定。多組位置用逗號分隔。",
      en: "Advanced setting. Separate multiple positions with commas.",
      ja: "記事右上の共有/ブラウザ起動ホットスポット。複数点はカンマ区切り。",
      ko: "기사 우측 상단 공유/브라우저 열기 핫스팟. 여러 점은 쉼표로 구분.",
    },
    wechatAgentConfigMenuHint: {
      "zh-CN": "高级设置。仅在自动采集不稳定时调整。",
      "zh-TW": "進階設定。僅在自動採集不穩定時調整。",
      en: "Advanced setting. Adjust only when auto collection is unstable.",
      ja: "共有点からの相対メニュー候補。リンクコピー/ブラウザ起動用。",
      ko: "공유 지점 기준 상대 메뉴 후보. 링크 복사/브라우저 열기용.",
    },
    wechatAgentConfigInterval: {
      "zh-CN": "循环间隔 (秒)",
      "zh-TW": "循環間隔 (秒)",
      en: "Loop Interval (sec)",
      ja: "ループ間隔 (秒)",
      ko: "루프 간격 (초)",
    },
    wechatAgentConfigMinFileSize: {
      "zh-CN": "最小截图体积 (KB)",
      "zh-TW": "最小截圖大小 (KB)",
      en: "Min Capture Size (KB)",
      ja: "最小キャプチャサイズ (KB)",
      ko: "최소 캡처 크기 (KB)",
    },
    wechatAgentPreviewCapture: {
      "zh-CN": "截图校准预览",
      "zh-TW": "截圖校準預覽",
      en: "Capture Preview",
      ja: "キャプチャ校正プレビュー",
      ko: "캡처 보정 미리보기",
    },
    wechatAgentPreviewOCR: {
      "zh-CN": "内容预览",
      "zh-TW": "內容預覽",
      en: "Content Preview",
      ja: "内容プレビュー",
      ko: "내용 미리보기",
    },
    wechatAgentPreviewImage: {
      "zh-CN": "预览截图",
      "zh-TW": "預覽截圖",
      en: "Preview Image",
      ja: "プレビュー画像",
      ko: "미리보기 이미지",
    },
    wechatAgentPreviewSize: {
      "zh-CN": "截图体积",
      "zh-TW": "截圖大小",
      en: "Capture Size",
      ja: "キャプチャサイズ",
      ko: "캡처 크기",
    },
    wechatAgentPreviewOCRTitle: {
      "zh-CN": "内容预览",
      "zh-TW": "內容預覽",
      en: "Content preview",
      ja: "内容認識結果",
      ko: "내용 인식 결과",
    },
    wechatAgentPreviewOCRQuality: {
      "zh-CN": "质量判定",
      "zh-TW": "品質判定",
      en: "Quality",
      ja: "品質判定",
      ko: "품질 판정",
    },
    wechatAgentPreviewOCRQualityOK: {
      "zh-CN": "通过",
      "zh-TW": "通過",
      en: "Pass",
      ja: "合格",
      ko: "통과",
    },
    wechatAgentPreviewOCRQualityBad: {
      "zh-CN": "不通过",
      "zh-TW": "不通過",
      en: "Fail",
      ja: "不合格",
      ko: "실패",
    },
    wechatAgentPreviewOCRReason: {
      "zh-CN": "原因",
      "zh-TW": "原因",
      en: "Reason",
      ja: "理由",
      ko: "사유",
    },
    wechatAgentPreviewOCRProvider: {
      "zh-CN": "识别来源",
      "zh-TW": "識別來源",
      en: "Source",
      ja: "認識ソース",
      ko: "인식 출처",
    },
    wechatAgentPreviewOCRBody: {
      "zh-CN": "正文预览",
      "zh-TW": "正文預覽",
      en: "Body Preview",
      ja: "本文プレビュー",
      ko: "본문 미리보기",
    },
    wechatAgentPreviewOCRKeywords: {
      "zh-CN": "关键词",
      "zh-TW": "關鍵詞",
      en: "Keywords",
      ja: "キーワード",
      ko: "키워드",
    },
    wechatAgentHealthCheck: {
      "zh-CN": "健康检查",
      "zh-TW": "健康檢查",
      en: "Health Check",
      ja: "ヘルスチェック",
      ko: "상태 점검",
    },
    wechatAgentSelfHeal: {
      "zh-CN": "一键修复",
      "zh-TW": "一鍵修復",
      en: "Self Heal",
      ja: "自動修復",
      ko: "자동 복구",
    },
    wechatAgentHealthHealthy: {
      "zh-CN": "健康",
      "zh-TW": "健康",
      en: "Healthy",
      ja: "正常",
      ko: "정상",
    },
    wechatAgentHealthUnhealthy: {
      "zh-CN": "异常",
      "zh-TW": "異常",
      en: "Unhealthy",
      ja: "異常",
      ko: "이상",
    },
    wechatAgentHealthReasons: {
      "zh-CN": "异常原因",
      "zh-TW": "異常原因",
      en: "Reasons",
      ja: "理由",
      ko: "사유",
    },
    wechatAgentHealthCheckedAt: {
      "zh-CN": "检查时间",
      "zh-TW": "檢查時間",
      en: "Checked At",
      ja: "確認時刻",
      ko: "확인 시각",
    },
    wechatAgentConfigHealthStale: {
      "zh-CN": "健康阈值 (分钟)",
      "zh-TW": "健康閾值 (分鐘)",
      en: "Health Stale (min)",
      ja: "ヘルス閾値 (分)",
      ko: "건강 임계값 (분)",
    },
    refresh: {
      "zh-CN": "刷新状态",
      "zh-TW": "刷新狀態",
      en: "Refresh",
      ja: "更新",
      ko: "새로고침",
    },
    flushPending: {
      "zh-CN": "补偿 Pending",
      "zh-TW": "補償 Pending",
      en: "Flush Pending",
      ja: "Pending補完",
      ko: "Pending 보정",
    },
    retryFailed: {
      "zh-CN": "重试 Failed",
      "zh-TW": "重試 Failed",
      en: "Retry Failed",
      ja: "Failed再試行",
      ko: "Failed 재시도",
    },
    generateDaily: {
      "zh-CN": "生成日报",
      "zh-TW": "生成日報",
      en: "Generate daily summary",
      ja: "日報生成",
      ko: "일일 보고서 생성",
    },
    copy: {
      "zh-CN": "复制内容",
      "zh-TW": "複製內容",
      en: "Copy content",
      ja: "内容をコピー",
      ko: "내용 복사",
    },
    statusTitle: {
      "zh-CN": "24h 采集状态",
      "zh-TW": "24h 採集狀態",
      en: "24h Collector Status",
      ja: "24時間ステータス",
      ko: "24시간 수집 상태",
    },
    failedTitle: {
      "zh-CN": "失败列表",
      "zh-TW": "失敗列表",
      en: "Failed Items",
      ja: "失敗一覧",
      ko: "실패 목록",
    },
    failedEmpty: {
      "zh-CN": "当前没有失败项。",
      "zh-TW": "目前沒有失敗項。",
      en: "No failed items.",
      ja: "失敗項目はありません。",
      ko: "실패 항목이 없습니다.",
    },
    dailyTitle: {
      "zh-CN": "日报摘要",
      "zh-TW": "日報摘要",
      en: "Daily Summary",
      ja: "日次サマリー",
      ko: "일일 요약",
    },
    markdownPlaceholder: {
      "zh-CN": "点击“生成日报”后显示内容。",
      "zh-TW": "點擊「生成日報」後顯示內容。",
      en: "Generated content will appear here.",
      ja: "生成内容がここに表示されます。",
      ko: "생성된 내용이 여기에 표시됩니다.",
    },
    total: {
      "zh-CN": "总数",
      "zh-TW": "總數",
      en: "Total",
      ja: "合計",
      ko: "총계",
    },
    ready: {
      "zh-CN": "已完成",
      "zh-TW": "已完成",
      en: "Ready",
      ja: "完了",
      ko: "완료",
    },
    pending: {
      "zh-CN": "处理中",
      "zh-TW": "處理中",
      en: "Pending",
      ja: "処理中",
      ko: "처리중",
    },
    failed: {
      "zh-CN": "失败",
      "zh-TW": "失敗",
      en: "Failed",
      ja: "失敗",
      ko: "실패",
    },
    ocr: {
      "zh-CN": "内容补录",
      "zh-TW": "內容補錄",
      en: "Content recovery",
      ja: "内容補完",
      ko: "내용 보완",
    },
    messageCopied: {
      "zh-CN": "内容已复制到剪贴板。",
      "zh-TW": "內容已複製到剪貼簿。",
      en: "Content copied to clipboard.",
      ja: "内容をクリップボードにコピーしました。",
      ko: "내용이 클립보드에 복사되었습니다.",
    },
    source: {
      "zh-CN": "来源",
      "zh-TW": "來源",
      en: "Source",
      ja: "ソース",
      ko: "출처",
    },
    titleCol: {
      "zh-CN": "标题",
      "zh-TW": "標題",
      en: "Title",
      ja: "タイトル",
      ko: "제목",
    },
    error: {
      "zh-CN": "错误",
      "zh-TW": "錯誤",
      en: "Error",
      ja: "エラー",
      ko: "오류",
    },
};

export function localText(language: AppLanguage, key: string): string {
  return pickText(language, COLLECTOR_OPS_COPY[key] || {}, key);
}
